name: Build Astrology Calendar

on:
  workflow_dispatch:   # manual run only

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install ics

      - name: Run Astrology builder
        run: python build_astrology.py

      - name: Commit astrology calendar
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add calendar/astrology_events.ics
          git commit -m "Add astrology events ICS" || echo "No changes"
          git push
