name: Build Astrology Calendar

on:
  workflow_dispatch:        # manual run button
  push:
    paths:
      - "data/astrology_events.csv"
      - "build_astrology.py"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # build_astrology.py must read from data/astrology_events.csv
      # and write to calendar/astrology_events.ics (which yours does)
      - name: Run Astrology builder
        run: python build_astrology.py

      # 💥 no rebases, no merges — just force push the generated ICS
      - name: Commit astrology calendar (force push)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add calendar/astrology_events.ics
          git commit -m "Update astrology events ICS" || echo "No changes"
          git push --force

      - name: Upload astrology .ics as artifact
        uses: actions/upload-artifact@v4
        with:
          name: astrology-events-ics
          path: calendar/astrology_events.ics
