name: Update ICS

on:
  workflow_dispatch:     # lets you run it manually if needed
  push:                  # runs on code changes
  schedule:
    - cron: "0 12 * * 1"   # every Monday at 12:00 UTC (~8am ET)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests astral

      - name: Run ICS builder
        run: python build_ics.py

      - name: Commit calendar
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add calendar/ng_risk_calendar.ics
          git commit -m "Update ICS $(date -u +'%Y-%m-%d %H:%M:%SZ')" || echo "No changes to commit"
          git push
