name: Build ICS

on:
  workflow_dispatch:   # lets you run it manually
  push:                # also runs whenever you push new code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run ICS builder
        run: python build_ics.py

            - name: Upload ICS file
        uses: actions/upload-artifact@v4
        with:
          name: calendar
          path: calendar.ics
